services:
  database:
    image: postgres:16
    container_name: vending-machine-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', '${DB_NAME}']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

