FROM node:19.5.0-alpine

# Set working directory
WORKDIR /frontend

# Install dependencies
COPY frontend/package*.json ./

# Copy project files
COPY frontend/ .

# Build the Next.js app
RUN rm -rf package-lock.json node_modules
RUN npm install
RUN npm run build

# Expose port
EXPOSE 3000

# Command to run the app
CMD ["npm", "start"]
