version: "3"
services:
  frontend:
    build:
      context: ../
      dockerfile: deployment/dockerfile.frontend
    depends_on:
      - database 
      # - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3000:3000"
    networks:
      - vending-machine-network

  database:
    image: postgres:16
    container_name: vending-machine-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DB_NAME}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - vending-machine-network

  backend:
    env_file: .env
    build:
      context: ../
      dockerfile: deployment/dockerfile.backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=${BACKEND_PORT}
    networks:
      - vending-machine-network

networks:
  vending-machine-network:
    driver: bridge
